feat: 一些小改进
FEMessage/count-down pull request #6
Opened 2019-11-01 03:53 UTC by shoyuf

## Why
使用过程中发现的几个问题
1. format 和 slot 表现的结果不一致（slot 内的时间数据没有补齐）
1. slot 内的 millisecond 补齐3位（避免毫秒在有背景色的情况下显示宽度一直在抖动）
1. props 没有支持到 millisecond （这个也许可以有）
1. 新增 timestamp prop（方便在服务端直接返回截止时间的情况下直接使用组件）

## How
Detail in commits 🤙

## Test
https://github.com/FEMessage/count-down/compare/dev...shoyuf:dev#diff-d5a5c858fb7261c905d152bd5ed0c9d2

## Docs
Already changed in api documents

2019-11-04 06:26 UTC, levy9527 commented
1.怎么有 breaking change
2.时间戳同时支持10位与13位是出于什么考虑。

2019-11-04 12:05 UTC, shoyuf commented
> 1.为何会有 breaking change
> 2.时间戳同时支持10位与13位是出于什么考虑。

1. https://github.com/FEMessage/count-down/pull/6/files#diff-34a6d62af0cf0b784f8444529f3130efR56 

timeFormatter 没有对天数进行格式化，之前一位的天数会自动在前面添加0，而现在表现为不自动加0

2. 时间戳支持10和13位出于对服务端返回的秒和毫秒两种类型时间戳进行兼容

2019-11-05 13:43 UTC, donaldshen commented on docs/timestamp.md
> +  <count-down :timestamp="(()=>new Date().getTime() + 3600000)()" />
假设服务器传的是截止时间戳，那么传`:seconds="(timestamp - Date.now()) / 1000"`即可

2019-11-05 13:44 UTC, donaldshen commented on src/count-down.vue
> +        if (len === 13 || len === 10) {
0到13位都有可能呀

2019-11-05 13:45 UTC, donaldshen commented on src/util.js
> +  days: 60 * 60 * 24 * 1000,
如果都乘以1000，那么名字就该叫`millisecondsIn`了……

2019-11-05 13:48 UTC, donaldshen commented on src/count-down.vue
> +    milliseconds: {
这个可以有

2019-11-05 13:49 UTC, donaldshen commented on src/util.js
> +export function toMilliseconds(
这个函数现在藏了两套完全不同的逻辑。

2019-11-05 13:54 UTC, donaldshen commented on src/util.js
> +  if (key === 'hours' || key === 'minutes' || key === 'seconds') {
days没有处理。似乎是你有意的，为啥哩

2019-11-05 13:56 UTC, donaldshen requested changes
建议保留milliseconds这个prop，其他像timestamp这样的改动就没必要了

2019-11-06 01:58 UTC, shoyuf commented on docs/timestamp.md
> +  <count-down :timestamp="(()=>new Date().getTime() + 3600000)()" />
Good idea !

2019-11-06 02:11 UTC, donaldshen commented on src/count-down.vue
> +    milliseconds: {
之前没有加毫秒的考虑是：已经有`:seconds="time / 1000"`这种写法了；再加个`:milliseconds="time"`似乎没有节省字符数……

2019-11-06 02:16 UTC, donaldshen commented on src/util.js
> +    timeData[k] = timeFormatter(k, Math.floor(time / v))
slot的用途是方便用户自定义处理倒计时数据的，所以会传原始数据。补了0变成字符串，定制就麻烦了些

2019-11-06 02:25 UTC, shoyuf commented
1. format 和 slot 表现的结果不一致（slot 内的时间数据没有补齐）
1. slot 内的 hours, minutes, seconds, milliseconds 补齐（同时避免毫秒在有背景色的情况下显示宽度一直在抖动）

这两个commit需要讨论一下

1. 第一个问题包含两个问题
    1. format prop 不支持ms
    2. 之前使用format prop和slot，在相同传入参数情况下，表现结果不一致

案例：
```vue
<count-down :seconds="59" :days="1" format="dd天 hh:mm:ss.ms" />
```
修改前输出 `01天 00:00:59`
修改后输出 `1天 00:00:59.000`

```vue
<count-down :seconds="59" :days="1">
<template v-slot="{days,hours,minutes,seconds,milliseconds}">
{{`${days}天 ${hours}:${minutes}:${seconds}.${milliseconds}`}}
</template>
</count-down>
```
修改前输出：`1天 0: 0:59.0` 
修改后输出：`1天 00: 00:59.000`

1. 第二个问题如图，时分秒在降到个位数时宽度不易控制，但主要问题还是第一个问题的不一致情况
![](https://bucket-showyu.oss-cn-beijing.aliyuncs.com/article/test/%E6%88%AA%E5%B1%8F2019-11-06%E4%B8%8A%E5%8D%8810.19.09.png)

2019-11-06 02:33 UTC, lianghx-319 commented
> 1. format 和 slot 表现的结果不一致（slot 内的时间数据没有补齐）
> 2. slot 内的 hours, minutes, seconds, milliseconds 补齐（同时避免毫秒在有背景色的情况下显示宽度一直在抖动）
> 
> 这两个commit需要讨论一下
> 
> 1. 第一个问题包含两个问题
>    
>    1. format prop 不支持ms
>    2. 之前使用format prop和slot，在相同传入参数情况下，表现结果不一致
> 
> 案例：
> 
> ```
> <count-down :seconds="59" :days="1" format="dd天 hh:mm:ss.ms" />
> ```
> 
> 修改前输出 `01天 00:00:59`
> 修改后输出 `1天 00:00:59.000`
> 
> ```
> <count-down :seconds="59" :days="1">
> <template v-slot="{days,hours,minutes,seconds,milliseconds}">
> {{`${days}天 ${hours}:${minutes}:${seconds}.${milliseconds}`}}
> </template>
> </count-down>
> ```
> 
> 修改前输出：`1天 0: 0:59.0`
> 修改后输出：`1天 00: 00:59.000`
> 
> 1. 第二个问题如图，时分秒在降到个位数时宽度不易控制，但主要问题还是第一个问题的不一致情况
>    ![](https://camo.githubusercontent.com/05b10b922b6d60eed3ebc4c7d6bfd1762f51c6ba/68747470733a2f2f6275636b65742d73686f7779752e6f73732d636e2d6265696a696e672e616c6979756e63732e636f6d2f61727469636c652f746573742f254536253838254141254535254231253846323031392d31312d303625453425423825384125453525384425383831302e31392e30392e706e67)

1. ms 的 props 可以确认增加的
2. slot 原则上还是传源数据，需要处理补零的话，其实可以在外部用 filter。

2019-11-06 02:44 UTC, donaldshen commented
> 1. format 和 slot 表现的结果不一致（slot 内的时间数据没有补齐）
> 2. slot 内的 hours, minutes, seconds, milliseconds 补齐（同时避免毫秒在有背景色的情况下显示宽度一直在抖动）
> 
> 这两个commit需要讨论一下
> 
> 1. 第一个问题包含两个问题
>    
>    1. format prop 不支持ms
>    2. 之前使用format prop和slot，在相同传入参数情况下，表现结果不一致
> 
> 案例：
> 
> ```
> <count-down :seconds="59" :days="1" format="dd天 hh:mm:ss.ms" />
> ```
> 
> 修改前输出 `01天 00:00:59`
> 修改后输出 `1天 00:00:59.000`
> 
> ```
> <count-down :seconds="59" :days="1">
> <template v-slot="{days,hours,minutes,seconds,milliseconds}">
> {{`${days}天 ${hours}:${minutes}:${seconds}.${milliseconds}`}}
> </template>
> </count-down>
> ```
> 
> 修改前输出：`1天 0: 0:59.0`
> 修改后输出：`1天 00: 00:59.000`
> 
> 1. 第二个问题如图，时分秒在降到个位数时宽度不易控制，但主要问题还是第一个问题的不一致情况
>    ![](https://camo.githubusercontent.com/05b10b922b6d60eed3ebc4c7d6bfd1762f51c6ba/68747470733a2f2f6275636b65742d73686f7779752e6f73732d636e2d6265696a696e672e616c6979756e63732e636f6d2f61727469636c652f746573742f254536253838254141254535254231253846323031392d31312d303625453425423825384125453525384425383831302e31392e30392e706e67)

1. 使用format和直接输出slot的数据其表现当然是不同的；事实上slot可以捏成任何样式
2. 倒计时组件的一个经典场景是验证码，所以`<count-down :seconds="59" />`就可以直接输出"59秒"。加了毫秒之后，默认format就不合适这个场景了。

2019-11-06 04:45 UTC, shoyuf commented on src/util.js
> +  if (key === 'hours' || key === 'minutes' || key === 'seconds') {
我觉得天数没必要补0处理

2019-11-06 07:07 UTC, donaldshen approved these changes

2019-11-06 07:29 UTC, levy9527 commented
@all-contributors add @shoyuf code

2019-11-06 07:30 UTC, merged